In [1]:
import os
import pandas as pd
from experiments.modules.automated_crows_test import test_crows

crows_dir = "data/crows_improved/"
results = {}

# to_test_types = ["gender", "race-color", "religion"]
to_test_types = ["gender"]
# to_test_lang = ["ar_DZ", "ca_ES", "de_DE", "en_US", "es_AR", "fr_FR", "it_IT", "mt_MT", "zh_CN"]
to_test_lang = ["de_DE"]

for filename in os.listdir(crows_dir):
    filepath = os.path.join(crows_dir, filename)
    if os.path.isfile(filepath):
        lang = filepath[-9:-4]
        if lang not in to_test_lang:
            continue
        print(f"Testing {lang}")
        for btype in to_test_types:
            result = test_crows(
                path=filepath,
                bias_type=btype,
                model_name_or_path="bert-base-multilingual-uncased",
                verbose=False
            )
            results.setdefault(lang, {})[btype] = result

print(results)
df = pd.DataFrame.from_dict(results, orient="index")
df

Testing de_DE

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

  0%|          | 0/308 [00:00<?, ?it/s]

Metric: 62.83
{'de_DE': {'gender': 62.83}}

       gender
de_DE   62.83

In [4]:
import os
import pandas as pd
from experiments.modules.automated_crows_debias_test import test_crows_debias

crows_dir = "data/crows_improved/"
results = {}

# to_test_types = ["gender", "race-color", "religion"]
to_test_types = ["gender"]
# to_test_lang = ["ar_DZ", "ca_ES", "de_DE", "en_US", "es_AR", "fr_FR", "it_IT", "mt_MT", "zh_CN"]
to_test_lang = ["de_DE"]

for filename in os.listdir(crows_dir):
    filepath = os.path.join(crows_dir, filename)
    if os.path.isfile(filepath):
        lang = filepath[-9:-4]
        if lang not in to_test_lang:
            continue
        print(f"Testing {lang}")   
        for btype in to_test_types:     
            result = test_crows_debias(
                path_to_crows=filepath,
                lang_debias="en",
                lang_eval=lang,
                bias_type="gender",
                bias_direction="results/subspace/subspace_m-BertModel_c-bert-base-multilingual-uncased_t-gender_debias-en.pt",
                model_name_or_path="bert-base-multilingual-uncased",
                verbose=False
            )
            results.setdefault(lang, {})[btype] = result
    
print(results)
df = pd.DataFrame.from_dict(results, orient="index")
df

Testing de_DE

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

  0%|          | 0/308 [00:00<?, ?it/s]

{'de_DE': {'gender': 53.95}}

       gender
de_DE   53.95